---
database:
  name: pyslackersweb
  host: localhost
  port: 5432
  user: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    30633539333262623564653232633533656366353034326463643637353661666630376537333433
    3532343836346462323663326531363137636538616532330a653035386333343132376538636564
    34323463366464393832623433656437303332393931313937313063643761336535366363366331
    3664383234666331640a666264383033313766303433663831316364333831663665366433616236
    6532
  password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    37316239346139623238643630396566396638623336346333646136623238366134326365623736
    6565306561393632323631353866336532663365343965610a313262623734643264633630396235
    38646431386139666466666661646639623563336363383335376530373164623836333531336332
    3332623731326162630a666166613838656432356135356232373731653831386431363433326331
    37363833613361376464656563613564643930323062366236653435386565653266303030393336
    6630323766643865323864353966626636323334366464356533

secret_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35393065346233666663633363643232616636396232353961386661353764633431393266653337
  6434623432343266376330633530643161386533383339650a636238346261393434646133653734
  33343234666363303161616334333832326337613966633763666133393766626464646337313165
  3432386265343739610a323437663138323864346431346330326134666664653836643661653130
  37376239306163303038373436316639353434666631626333396466346131316532666436626133
  3931653639636636376262393665643661363736636632623930

slack:
  # general, introductions
  join_channels: C07EFBK3R,C07EHQYFN
  oauth_token: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    34346637303563663462663634353833393538333033303261613433636633653861376661306430
    6561623733383535373938626531633532373630393964390a343137376266336462343939333766
    31323234356334333961663432353235356565636538336163376166393337363130613531316366
    3738356633363437620a653839363466636234383835323363383433343663663335373639666232
    36643465316566613939653030383230323033376634636437373033663035343166643035623036
    64623830333335663664396163396564346661613438313733316632613962326533366566626435
    64313466666539363639646631323536653164343464376537643736366462393532626663313837
    31323133346538336537

appuser:
  name: pyslackersweb